
services:
  airflow-webserver:
    env_file:
      - .env
    image: apache/airflow:latest
    restart: always
    depends_on:
      - airflow-init
      - postgres
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__SMTP__SMTP_HOST=smtp.gmail.com
      - AIRFLOW__SMTP__SMTP_STARTTLS=True
      - AIRFLOW__SMTP__SMTP_SSL=False
      - AIRFLOW__SMTP__SMTP_PORT=587
      - AIRFLOW__SMTP__SMTP_USER=lalit.anand676@gmail.com
      - AIRFLOW__SMTP__SMTP_PASSWORD=qlqq nbng xeft vdfr
      - AIRFLOW__SMTP__SMTP_MAIL_FROM=lalit.anand676@gmail.com

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./datafiles/events:/opt/airflow/datafiles/events
      - ./dags/scripts:/opt/airflow/dags/scripts
      - ./datafiles/product_metadata:/opt/airflow/datafiles/product_metadata
      - ~/.aws:/home/airflow/.aws
      - ./config/airflow.cfg:/opt/airflow/airflow.cfg
    command: webserver

  airflow-scheduler:
    env_file:
      - .env
    image: apache/airflow:latest
    restart: always
    depends_on:
      - airflow-init
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__SMTP__SMTP_HOST=smtp.gmail.com
      - AIRFLOW__SMTP__SMTP_STARTTLS=True
      - AIRFLOW__SMTP__SMTP_SSL=False
      - AIRFLOW__SMTP__SMTP_PORT=587
      - AIRFLOW__SMTP__SMTP_USER=lalit.anand676@gmail.com
      - AIRFLOW__SMTP__SMTP_PASSWORD=qlqq nbng xeft vdfr
      - AIRFLOW__SMTP__SMTP_MAIL_FROM=lalit.anand676@gmail.com
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./datafiles/events:/opt/airflow/datafiles/events
      - ./dags/scripts:/opt/airflow/dags/scripts
      - ./datafiles/product_metadata:/opt/airflow/datafiles/product_metadata
      - ~/.aws:/home/airflow/.aws
      - ./config/airflow.cfg:/opt/airflow/airflow.cfg
    command: scheduler

  airflow-init:
    image: apache/airflow:latest
    restart: on-failure
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__SMTP__SMTP_HOST=smtp.gmail.com
      - AIRFLOW__SMTP__SMTP_STARTTLS=True
      - AIRFLOW__SMTP__SMTP_SSL=False
      - AIRFLOW__SMTP__SMTP_PORT=587
      - AIRFLOW__SMTP__SMTP_USER=lalit.anand676@gmail.com
      - AIRFLOW__SMTP__SMTP_PASSWORD=qlqq nbng xeft vdfr
      - AIRFLOW__SMTP__SMTP_MAIL_FROM=lalit.anand676@gmail.com
    command: ["airflow","db", "init"]

  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
